" Set important vim directories and file paths
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set runtimepath=~/.vim,~/.vim/after,$VIM,$VIMRUNTIME
set undodir=~/.vim/undo//
set viminfo='100,<50,s10,h,n~/.vim/viminfo
set tags=tags;

colorscheme elflord
syntax on

" Make working directory same as file
" set autochdir can break some plugins
autocmd BufEnter * silent! lcd %:p:h

" Make backspace work properly on all systems
" Alternative is to use 'set bs=2'
set backspace=indent,eol,start

" Allow opening new file when there are unsaved changes to buffer
set hidden

" No need for legacy vi support
set nocompatible

" Access files in all subfolders starting from current path
" E.g. ':file utils.c' where utils.c is in a subdirectory
set path+=**

" Display all matching files with tab complete
set wildmenu

" Display line number, relative numbers, and ruler
set number
set relativenumber
set ruler

" Place cursor in new window after splitting with :vsp
set splitright

" Set up proper indentation, spaces, and text width
set autoindent
set expandtab
set shiftwidth=4
set smarttab
set softtabstop=4
set tabstop=4
set textwidth=100

" Highlight all search matches
set hlsearch
" Start searching as you type
set incsearch
" Ignore case for searches
set ignorecase
" Case sensitive search when string contains uppercase char
set smartcase 

" in insert mode 'jk' will generate Escape
imap jk <Esc>

"" Directional split navigation
nmap <c-j> <c-w>j
nmap <c-k> <c-w>k
nmap <c-h> <c-w>h
nmap <c-l> <c-w>l

function TrimWhiteSpace()
  let l:save = winsaveview()
  :s/\s\+$//e
  call winrestview(l:save)
endfunction

" This would automatically trim whitespace every time the buffer is written for specific file types
" autocmd FileType c,python,text autocmd BufWritePre <buffer> :call TrimWhiteSpace()<CR>

noremap <F12> :call TrimWhiteSpace()<CR>

autocmd FileType gitcommit setlocal spell textwidth=72 colorcolumn=73
autocmd BufNewFile,BufRead *.inc set filetype=sh

" Use F2 to toggle paste mode on and off, with some visual feedback in normal mode
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode

" Specify a directory for plugins
call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-fugitive'
Plug 'christoomey/vim-tmux-navigator'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'


" Plugin outside ~/.vim/plugged with post-update hook
" Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }


" Initialize plugin system
call plug#end()
